---
title       : Introduction to International Political Economy
subtitle    : Justin Murphy, University of Southampton
author      : jmrphy.net
job         : '@jmrphy'
framework   : io2012    # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
---
## The Goal

To give you a roadmap of what we think we know in IPE today, while emphasising the most important questions we still need to find answers for (that means you!)
> - I'm going to try to cover a lot of ground, but don't worry
> - I'll point you to lots of key names and readings for you to pursue as you please
> - These slides are available to you online:
    - [jmrphy.net/intro_ipe](jmrphy.net/intro_ipe)
> - And here you can find all the texts I mention in this lecture:
    - [bit.ly/intro_ipe](bit.ly/intro_ipe)

---

## The Plan
> 1. A short history of IPE

> 2. Some things we think we know

> 3. Some things we don't know (but need to)

---

## A Short History of IPE

> 1. For most of human history, the study of international political economy was a humanist tradition
  - Basically, it refers to old white men with classical educations ruminating
  - A combination of law, philosophy, politics, and economics
  
> 2. Only in the early 1970s is "IPE" established as a specific field of the social sciences
  - Combines mainstream economics with political analysis
  - Emphasises scientific hypotheses which can be tested against empirical data
  - In the "British School", big names include Robert Cox and Susan Strange, etc.
  - In American IPE, big names include Gilpin, Keohane, Kindleberger, etc.

---

## What have we learned from modern IPE as a social science?

> 1. Our strongest findings are based on economic theory, and modeled as such
    - Known as "open economy politics" (Lake 2006)
    - They emphasise rational, strategic actors competing
    - They tend to be formal, specific, and quantitative
> 2. The distributive political effects of international economics
    - Example: increasing economic integration benefits certain domestic groups and harms others (Frieden and Rogowski 1996)
> 3. The international effects of domestic politics
    - Example: domestic politics shape interntional economic policy (Mansfield, Milner, Rosendorff 2000)

---

## But who is this good for?

> 1. Mainstream IPE is the epitome of "bourgeois political economy"

> 2. It does not speak truth to power!

> 3. It speaks the truth *of* power, *for* power

> 4. But we can use IPE to decipher power, rebel, and change the world

---

## Globalization and/or neoliberalism?

> 1. Since the 1990s, all we hear about is "globalization"
    - The increasingly free flow of capital, goods and services around the globe
    - We're told this is an international pressure forcing the hands of governments (Hay and Rosamond 2002)

> 2. But it tends to ignore or downplay the "neoliberal revolution" of the 1970s and 1980s
    - When rich U.S. elites and economists decided to wage class war on the globe
    - Ever since, national oligarchies have emerged and become a global elite
    - Citizens everywhere are losing democratic control of politicians
    - IPE remains rather happily unconcerned with all of this

> 3. How can we use the tools of IPE to better understand this global social war?

---

## Globalization vs. neoliberalism, some directions

> "Free trade agreements" seem to be less and less about "free trade""
  > - More about increasing rights of capital over citizens
  > - "What can we change to make the rich in both countries happier?"
  > - Investors' rights and intellectual property
  > - Often shrouded in lies and secrecy
  > - Examples: NAFTA, TPP

---

## Globalization vs. neoliberalism, some directions

> And as states open internationally, they also (sometimes):
  > - Cut essential welfare spending (Burgoon 2001; Rudra 2002)
  > - Repress and torture dissidents (Klein 2010)
  > - Make the rich richer (Freeland)
  > - Make it harder for citizens to hold them accountable for the economy (Hellwig and Samuels 2007)
  > - Use the media as cover, or repress it (me)
  
> We *really* need to understand these things better!

---

## Thank you!

- My website is at [jmrphy.net](jmrphy.net)

- Find me on twitter, [http://twitter.com/jmrphy](twitter.com/jmrphy)

- These slides are available to you online:
    - [jmrphy.net/intro_ipe](jmrphy.net/intro_ipe)
    
- And here you can find all the texts I mention in this lecture:
    - [bit.ly/intro_ipe](bit.ly/intro_ipe)





